name: publish

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+*"]

jobs:
  # https://dart.dev/tools/pub/automated-publishing
  publish:
    # uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
    runs-on: ubuntu-latest
    permissions: {id-token: write}
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
      - run: dart pub get
      - run: dart pub publish --dry-run
      - run: dart pub publish --force
