name: review

on:
  workflow_call:

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: flutter-actions/setup-flutter@v3
        with: {version: "3.19.6"}
      - run: flutter pub get
      - run: flutter publish --dry-run
      - run: flutter publish --force
