name: review

on:
  workflow_call:

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - run: go get ./...
      - run: go vet ./...
      - run: go build ./...
      - run: go test -race ./...
